# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
